### ISSUE TITLE
Hyphens, i.e. `-` in a query parameter name raise an exception.

### ISSUE THREAD

**Issue by colinrymer** [grncdr/uri-template#14]
Using this library to parse a template results in the following error:

```
Failed to parse URI template: /api/versions{?api-version}
 Error: SyntaxError: Expected "(", "*", ",", ":", "}" or [a-zA-Z0-9_.%] but "-" 
```

I'm happy to provide more information if necessary, but a cursory glance at this repo makes it seem like adding `-` to https://github.com/grncdr/uri-template/blob/master/index.pegjs#L22 would resolve this.

**Comment by andreineculau** [comment]
Please provide a reference to RFC 6570 where hyphen is specified as a valid parameter character. I don't see it.

**Comment by c0** [comment]
It's a part of the `unreserved` set:

`unreserved     =  ALPHA / DIGIT / "-" / "." / "_" / "~"`

https://tools.ietf.org/html/rfc6570

**Comment by andreineculau** [comment]
`unreserved` is irrelevant. Meanwhile I looked at RFC 6570 myself.

```
     variable-list =  varspec *( "," varspec )
     varspec       =  varname [ modifier-level4 ]
     varname       =  varchar *( ["."] varchar )
     varchar       =  ALPHA / DIGIT / "_" / pct-encoded
```

 `varchar` says "-" is not a valid parameter character. Closing, and https://github.com/apiaryio/dredd/issues/460 should be closed as well IMO.

**Comment by armen-ch** [comment]
Sorry for activating this long ago closed discussion but it's really important for integrating Dredd into our api validation process. As Caleb Wright mentioned and it's also stated in https://datatracker.ietf.org/doc/html/rfc3986#section-2.3 from which RFC 6570 is derived btw hyphen is a valid unreserved character for URIs. I came across different articles in the internet which declare hyphen as a valid query parameter character e.g; https://en.wikipedia.org/wiki/Query_string, https://developers.google.com/maps/url-encoding , https://www.oreilly.com/library/view/restful-web-services/9780596809140/ch04.html , https://stackoverflow.com/questions/32348875/can-hyphens-be-used-in-query-string-values . Moreover it is highly encouraged to use hyphens instead of underscores when designing URI :  https://developers.google.com/search/docs/advanced/guidelines/url-structure#:~:text=We%20recommend%20that%20you%20use,(%20_%20)%20in%20your%20URLs.

We have dozens of microservices which uses hyphens in URIs in URL paths as well as in query parameter names and values and we can't use dredd because of this problem. Can you please disable this validation or maybe allow to disable it via option or configuration, Please let me know if I need to create a new issue. Thanks in advance!
